/*
Creación de trigger rnamadm
autor JLCR
Fecha: FEB 2024
*/

create or replace TRIGGER tr_rnam_pacientes
BEFORE INSERT ON RNAM_PACIENTES
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_PACIENTES.NEXTVAL INTO :new.ID_RNAM_PACIENTE FROM dual;
END;
/
create or replace TRIGGER tr_rnam_usuarios_tok
BEFORE INSERT ON RNAM_CAT_USUARIOS_TOKEN
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_USUARIOS_TOK.NEXTVAL INTO :new.ID_RNAM_usuario FROM dual;
END;
/
create or replace TRIGGER tr_rnam_responsables
BEFORE INSERT ON RNAM_RESPONSABLES
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_RESPONSABLES.NEXTVAL INTO :new.ID_responsable FROM dual;
END;
/
create or replace TRIGGER tr_rnam_contactos
BEFORE INSERT ON RNAM_CONTACTOS
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_CONTACTOS.NEXTVAL INTO :new.ID_contacto FROM dual;
END;
/
create or replace TRIGGER tr_rnam_telefonos_pacientes
BEFORE INSERT ON RNAM_TELEFONOS_PACIENTES
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_TEL_PACIENTES.NEXTVAL INTO :new.ID_telefono_paciente FROM dual;
END;
/
create or replace TRIGGER tr_rnam_telefonos_responsables
BEFORE INSERT ON RNAM_TELEFONOS_responsables
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_TEL_RESPONSABLE.NEXTVAL INTO :new.ID_TELEFONO_RESPONSABLE FROM dual;
END;
/
create or replace TRIGGER tr_RNAM_TELEFONOS_CONTACTOS
BEFORE INSERT ON RNAM_TELEFONOS_CONTACTOS
FOR EACH ROW
BEGIN
SELECT RNAM_SEQ_TEL_CONTACTOS.NEXTVAL INTO :new.ID_TELEFONO_CONTACTO FROM dual;
END;