/*
Creación de synonymos rnamadm
autor JLCR
Fecha: FEB 2024
*/

CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_INSTITUCIONES_MEDICAS FOR rnamadm.RNAM_CAT_INSTITUCIONES_MEDICAS;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_NACIONALIDADES FOR rnamadm.RNAM_CAT_NACIONALIDADES;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_SEMAFORO FOR rnamadm.RNAM_CAT_SEMAFORO;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_SEXOS FOR rnamadm.RNAM_CAT_SEXOS;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_TIPOS_TELEFONOS FOR rnamadm.RNAM_CAT_TIPOS_TELEFONOS;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CAT_USUARIOS_TOKEN FOR rnamadm.RNAM_CAT_USUARIOS_TOKEN;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_CONTACTOS FOR rnamadm.RNAM_CONTACTOS;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_PACIENTES FOR rnamadm.RNAM_PACIENTES;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_RESPONSABLES FOR rnamadm.RNAM_RESPONSABLES;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_TELEFONOS_CONTACTOS FOR rnamadm.RNAM_TELEFONOS_CONTACTOS;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_TELEFONOS_PACIENTES FOR rnamadm.RNAM_TELEFONOS_PACIENTES;
CREATE OR REPLACE SYNONYM rnamapp.RNAM_TELEFONOS_RESPONSABLES FOR rnamadm.RNAM_TELEFONOS_RESPONSABLES;