/*
Creación de GRANT rnamadm
autor JLCR
Fecha: FEB 2024
*/

GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_INSTITUCIONES_MEDICAS to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_NACIONALIDADES to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_SEMAFORO to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_SEXOS to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_TIPOS_TELEFONOS to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CAT_USUARIOS_TOKEN to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_CONTACTOS to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_PACIENTES to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_RESPONSABLES to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_TELEFONOS_CONTACTOS to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_TELEFONOS_PACIENTES to rnamapp;
GRANT SELECT,INSERT,UPDATE ON rnamapp.RNAM_TELEFONOS_RESPONSABLES to rnamapp;